### Get Report Types
GET http://localhost:3007/api/report/types
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY4ZDQ4N2Q1ZDQ1MTk0Mzg5NzNlNTEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDA2NiIsImlhdCI6MTcxMDgwNjE1MSwiZXhwIjoxNzEzMzk4MTUxfQ.ejzHSxPZr80o09g2UXinerDNq7cUrP3hO7Ere9m_1fM

### Report a Post
GET http://localhost:3007/api/report/65f8d8de3e6366b7190153ce/report/NOT_FOUND
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY4ZDQ4N2Q1ZDQ1MTk0Mzg5NzNlNTEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDA2NiIsImlhdCI6MTcxMDgwNjE1MSwiZXhwIjoxNzEzMzk4MTUxfQ.ejzHSxPZr80o09g2UXinerDNq7cUrP3hO7Ere9m_1fM

### Get Post Report Count
GET http://localhost:3007/api/report/65f8d8de3e6366b7190153ce/counts
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY4ZDQ4N2Q1ZDQ1MTk0Mzg5NzNlNTEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDA2NiIsImlhdCI6MTcxMDgwNjE1MSwiZXhwIjoxNzEzMzk4MTUxfQ.ejzHSxPZr80o09g2UXinerDNq7cUrP3hO7Ere9m_1fM

### Get User Post Report
GET http://localhost:3007/api/report/65f8d8de3e6366b7190153ce/user
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY4ZDQ4N2Q1ZDQ1MTk0Mzg5NzNlNTEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDA2NiIsImlhdCI6MTcxMDgwNjE1MSwiZXhwIjoxNzEzMzk4MTUxfQ.ejzHSxPZr80o09g2UXinerDNq7cUrP3hO7Ere9m_1fM

